# Site settings
title: Sviatoslav Belmeha # site title
description: >- # site description
  Here I write some notes about iOS development, 
  also you can find some shorter version of them in my <a href="https://twitter.com/lan_dsv" target="_blank" rel="noopener">@twitter</a>.
lang: en-US # default lang
timezone: Europe/Kiev # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/piharpi/jekyll-klise # site repo [optional]
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: Sviatoslav Belmeha # author name
  bio: >- # tell to the world
    Here I write some notes about iOS development, 
    also you can find some shorter version of them in my <a href="https://twitter.com/lan_dsv" target="_blank" rel="noopener">@twitter</a>.
  username: landsv # social media username eg. github, twitter 
  email: belmeha@gmail.com # your contact adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# Url settings
url: "https://klise.now.sh"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
